# compose.yaml

x-custom-variables:
  # Update version to match client in pyproject.toml
  # fallback to 9.0.0 if not set
  es-image: &es_img docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-9.0.0}
  kb-image: &kb_img docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-9.0.0}
  # ls-image: &ls_img docker.elastic.co/logstash/logstash:${ELASTIC_VERSION:-9.0.0}


services:
  elasticsearch:
    image: *es_img
    # Same thing as:
    # image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-9.0.0}
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      # Disable security for local development simplicity
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      # Cap JVM memory to keep your machine running smoothly
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic_network
    # Checks if ES is actually ready to accept connections
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5


  kibana:
    image: *kb_img
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elastic_network

# logstash:
#     image: *ls_img
#     container_name: logstash
#     depends_on:
#       elasticsearch:
#         condition: service_healthy
#     restart: unless-stopped
#     environment:
#       # Caps Logstash memory so it doesn't fight ES for RAM
#       - LS_JAVA_OPTS=-Xms512m -Xmx512m
#     volumes:
#       - ./logstash_config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
#     ports:
#       - "5044:5044"
#     networks:
#       - elastic_network

volumes:
  es_data:
    driver: local


networks:
  elastic_network:
    name: agent_sandbox_net # Custom network name for better isolation and debugging
    driver: bridge
