# compose.yaml

x-custom-variables:
  # Update version to match client in pyproject.toml
  # fallback to 9.0.0 if not set
  es-image: &es_img docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-9.0.0}
  kb-image: &kb_img docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-9.0.0}
  # ls-image: &ls_img docker.elastic.co/logstash/logstash:${ELASTIC_VERSION:-9.0.0}


services:
  elasticsearch:
    image: *es_img
    # Same thing as:
    # image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-9.0.0}
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      # Disable security for local development simplicity
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      # Cap JVM memory to keep your machine running smoothly
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      # - http.cors.enabled=true
      # - http.cors.allow-origin=*
      # - http.cors.allow-headers=X-Requested-With,Content-Type,Accept,Origin,Authorization
      # - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elastic_network
    # # Checks if ES is actually ready to accept connections
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -sf http://localhost:9200 || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  kibana:
    image: *kb_img
    container_name: kibana
    depends_on:
      - elasticsearch
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # # Disable monitoring
      # - xpack.reporting.enabled=false
      # - xpack.monitoring.enabled=false
      # - xpack.monitoring.collection.enabled=false
      # # Disable telemetry
      # - telemetry.enabled=false
      # - telemetry.optIn=false
    ports:
      - "5601:5601"
    networks:
      - elastic_network

# logstash:
#     image: *ls_img
#     container_name: logstash
#     restart: unless-stopped
#     # Caps Logstash memory so it doesn't fight ES for RAM
#     environment:
#       - LS_JAVA_OPTS=-Xms512m -Xmx512m
#     ports:
#       - "5044:5044"
#     volumes:
#       - ./logstash_config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
#     networks:
#       - elastic_network
#     depends_on:
#       elasticsearch:
#         condition: service_healthy


volumes:
  es_data:
    driver: local


networks:
  elastic_network:
    driver: bridge
